version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-node
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://wheretofindme@localhost/wheretofindme
      - image: circleci/postgres:11.1
        environment:
          POSTGRES_USER: wheretofindme
          POSTGRES_DB: wheretofindme

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

      - restore_cache:
          keys:
          - v1-dependencies-py-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          - v1-dependencies-py-

      - restore_cache:
          keys:
          - v1-dependencies-js-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - v1-dependencies-js-

      - run:
          name: Install Python dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev

      - run:
          name: Install Javascript dependencies
          command: |
            yarn

      - save_cache:
          paths:
            - ".venv"
          key: v1-dependencies-py-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
        
      - save_cache:
          paths:
            - "~/.cache/yarn"
            - "./node_modules/"
          key: v1-dependencies-js-{{ .Branch }}-{{ checksum "yarn.lock" }}
        
  test-server:
    docker:
      - image: circleci/python:3.7.2
      - image: circleci/postgres:11.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-py-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          - v1-dependencies-py-

      - run:
          name: run python tests
          command: |
            pipenv run test

  test-client:
    docker:
      - image: circleci/python:3.7.2-node

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-js-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - v1-dependencies-js-

      - run:
          name: run javascript tests
          command: |
            yarn js:test:unit

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test-server:
          requires:
            - build
      - test-client:
          requires:
            - build
